// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)


float anomaly_value;
bool boiler_state;
bool everything_ok;

void initProperties(){

  ArduinoCloud.addProperty(anomaly_value, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(boiler_state, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(everything_ok, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
